### ISSUE TITLE
Missing media and posters 

### ISSUE THREAD

**Issue by blake1725** [DestinationHome/Destination-Home-Online#213]
Mui mui ship public 
Dead island central public
granzella at twillight public
Hotzone midway public
Great edo of nippon public
Mall west public
Audi apartment 
audi alpine lodge public
seaside of memories public 
singstar store public 
Bomberman public 
and london pub there may be more that i havent seen

**Comment by blake1725** [comment]
all show for NA acc but not EU

**Comment by blake1725** [comment]
Silcone lounge apartment 
Mini space 
Action district 
hudson theatre 
no media play for EU accounts but works NA music, posters and video

**Comment by NagatoDEV** [comment]
Will look into some spaces this afternoon.

**Comment by NagatoDEV** [comment]
@blake1725 The following spaces screenlinks have been updated for the following regions: `es-ES` `en-GB` `fr-FR` `it-IT` `de-DE` 

- Red Bull Apartment
- x7 Entrance
- x7 (The actual club)
- Granzella Southern Hideaway
- Adventure District

Will be updating more this week, but I had some free time to get thsese done. If your free please test.

**Comment by blake1725** [comment]
london pub radio has the same issue where it plays for NA but not EU

**Comment by Tertie** [comment]
Since the issue with London pub radio got folded into this entry, I'll add my experience with it here.  I'm on NA account, and am able to hear the radio, and turn it on and off also.

A similar space, the Irish pub has a radio also.  But multiple people from NA and EU could not interact with it or hear the music.  So it seems like the Irish pub's radio is broken for everybody, but not the London pub radio.

**Comment by NagatoDEV** [comment]
Fixed the following spaces @Tertie @blake1725 

- Hudson Bomberman
- IREM Seaside (NA)
- Hotzone Midway.
- Mui Mui Ship (NA)

**Comment by blake1725** [comment]
![IMG_20191104_223631](https://github.com/DestinationHome/Destination-Home-Online/assets/132437520/b3c1035d-d56e-4190-bf2f-0a7c5d3715b7)

Bomberman still show black screen for me
Communtiy lounge shows black screen for NA account 
Loco island private media plays only for NA 
Sodium hub public

**Comment by cathoderaykobold** [comment]
Loco Island Notice Board is blank.
I'm making an educated guess that this is handled by a link to HTML, so I'm posting it here.
The board's contents can be found in this video:
https://youtu.be/yd8UssyQryU?t=95

**Comment by cathoderaykobold** [comment]
Loco Island's notice board is blank. I suspect it's an HTML link, so I'll leave a link to the issue in case you want to merge them.
https://github.com/DestinationHome/Destination-Home-Online/issues/240
